### python 라이브러리(패키지)
- 크롤링 : requests + BeautifulSoup / Selenium
- 데이터 분석 : pandas
- 숫자(배열, 행렬) 계산 : numpy
- 머신러닝 / 딥러닝 : scikit-learn, Pytorch, TensorFlow

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\source\pythonsource\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\source\pythonsource\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 5.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 5.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.9 MB 3.3 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/9.9 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 3.9 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.7 MB/s  0:00:01
Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 6.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.4 MB 5.5 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.4 MB 5.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.4 MB 4.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.4 MB 4.5 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.4 MB 5.1 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.4 MB 5.3 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.4 MB 5.2 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.4 MB 5.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.4 MB 4.7 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 4.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 4.7 MB/s  0:00:02
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.2 pandas-3.0.1 tzdata-2025.3

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Pandas
- 테이블 형태의 데이터를 다루는데 사용하는 데이터 분석 패키지
- 구조 - Series, DataFrame

In [1]:
import pandas as pd

In [2]:
series = pd.Series([70, 60, 90])
series

0    70
1    60
2    90
dtype: int64

In [4]:
series = pd.Series({"a":1, "b":2, "c":3})
series

a    1
b    2
c    3
dtype: int64

In [5]:
series = pd.Series([70, 60, 90], index=["국어", "수학", "영어"])
series

국어    70
수학    60
영어    90
dtype: int64

In [10]:
# 조회

print(series.국어)
print(series.index)
print(series.values)
print(series.shape) # (3, ) => 튜플
print(series.head(1))
print(series.tail(1))

70
Index(['국어', '수학', '영어'], dtype='str')
[70 60 90]
(3,)
국어    70
dtype: int64
영어    90
dtype: int64

In [13]:
# 수정
# index 수정
series.index = ["미술", "음악", "체육"]
series

# dtype: int64 => int 64비트(8byte) 표현
# java : int 4byte, long 8byte

# 타입변경
series = series.astype("int32")
series

미술    70
음악    60
체육    90
dtype: int32

In [14]:
# 제거
del series["미술"]
series

음악    60
체육    90
dtype: int32

In [15]:
# DataFrame : 가장 많이 사용

friend_dict_list = [
    {
        "name":"Jhon",
        "age":25,
        "job":"student"
    },
    {
        "name":"Nate",
        "age":30,
        "job":"teacher"
    },
    {
        "name":"Jenny",
        "age":30,
        "job":"developer"
    },
]

In [16]:
friend_df = pd.DataFrame(friend_dict_list)
friend_df

    name  age        job
0   Jhon   25    student
1   Nate   30    teacher
2  Jenny   30  developer

In [17]:
dict = {"국어":[15, 25, 35], "영어":[45, 55, 65], "수학":[36, 46, 56]}
student_df = pd.DataFrame(dict)
student_df

   국어  영어  수학
0  15  45  36
1  25  55  46
2  35  65  56

In [18]:
person_df = pd.DataFrame(friend_dict_list, index=["f1", "f2", "f3"])
person_df

     name  age        job
f1   Jhon   25    student
f2   Nate   30    teacher
f3  Jenny   30  developer

In [21]:
list1 = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]

two_df = pd.DataFrame(list1, index=["내용1", "내용2"], columns=["c1", "c2", "c3", "c4", "c5"])
two_df

     c1  c2  c3  c4  c5
내용1   1   2   3   4   5
내용2   6   7   8   9  10

In [25]:
# ms
sample_df1 = pd.read_csv("./data/sample1.csv", encoding="cp949")
sample_df1

   번호   이름                 가입일시  나이
0   1  김정수  2017-01-19 11:30:00  25
1   2  박민구  2017-02-07 10:22:00  35
2   3  정순미  2017-01-22 09:10:00  33
3   4  김정현  2017-02-22 14:09:00  45
4   5  홍미진  2017-04-01 18:00:00  17
5   6  김순철  2017-05-14 22:33:07  22
6   7  이동철  2017-03-01 23:44:45  27
7   8  박지숙  2017-01-11 06:04:18  30
8   9  김은미  2017-02-08 07:44:33  51
9  10  장혁철  2017-12-01 13:01:11  16

In [35]:
sample_df2 = pd.read_csv("./data/sample3.csv", encoding="cp949", delimiter="|", header=None)
sample_df2

   0    1                    2   3
0  1  김정수  2017-01-18 11:30:00  25
1  2  박민구  2017-02-07 10:22:00  35
2  3  정순미  2017-01-22 09:10:00  33
3  4  김정현  2017-02-22 14:30:00  45
4  5  홍미진  2017-01-18 11:30:00  24
5  6  이동철  2017-03-01 23:30:00  27
6  7  김은미  2017-04-01 23:30:00  25

In [36]:
file_df = pd.read_excel("./data/file1.xlsx")
file_df

    2  35  51  88    6  22  86  88.1   3  27
0   0  42  31  94    8  12  49    84  86  64
1  66  39  50   5   67  76  80    82  59  58
2  89  83  23  28  100  22  24    68  30  83
3  81  59  84  60    7  98  56    83  49  29
4  33  78  36  85   44  21  86    25  89  15
5  28   8  17  72   12  83  51    94  26  92
6  86  40  65  98   66  59  87    66  25   9
7  19  13   8  39   79  29  86    43   6  95
8   3  94  48   5   83  12  43    47   4  49

In [40]:
# 컬럼 조회
print(friend_df.columns)
print(friend_df.age)

# 필드명이 한글인 경우
print(friend_df['age'])

Index(['name', 'age', 'job'], dtype='str')
0    25
1    30
2    30
Name: age, dtype: int64
0    25
1    30
2    30
Name: age, dtype: int64

In [47]:
# Nate 정보만 추출 : 슬라이싱
friend_df.loc[0:1]

   name  age      job
0  Jhon   25  student
1  Nate   30  teacher

In [64]:
student_df.loc[1:2]

   국어  영어  수학
1  25  55  46
2  35  65  56

In [49]:
# 이름 기반
student_df.loc[1:2, "국어"]

1    25
2    35
Name: 국어, dtype: int64

In [52]:
# iloc : index location
student_df.iloc[1:3, 0]

1    25
2    35
Name: 국어, dtype: int64

In [53]:
person_df

     name  age        job
f1   Jhon   25    student
f2   Nate   30    teacher
f3  Jenny   30  developer

In [59]:
person_df.loc["f1":"f2", "age"]

f1    25
f2    30
Name: age, dtype: int64

In [61]:
person_df.iloc[0:2, 1]

f1    25
f2    30
Name: age, dtype: int64

In [63]:
# friend_df 에서 age >= 30 조회
friend_df[friend_df.age >= 30]

    name  age        job
1   Nate   30    teacher
2  Jenny   30  developer

In [65]:
# 25 보다 크고, 이름이 Nate 인 사람 조회
# python : age > 25 and name == 'Nate'

friend_df[(friend_df.age > 25)&(friend_df.name == 'Nate')]

   name  age      job
1  Nate   30  teacher

In [66]:
friend_df.query("age > 25" and "name == 'Nate'")

   name  age      job
1  Nate   30  teacher

In [67]:
student_df[student_df.국어>20]

   국어  영어  수학
1  25  55  46
2  35  65  56

In [69]:
# sample.xlsx => sample_df 로 생성
sample_df = pd.read_excel("./data/sample.xlsx")
sample_df

   Sap Co.        대리점 영업사원       전월       금월  TEAM  총 판매수량
0   KI1316    경기수원대리점  이기정  1720000  2952000     1     123
1   KI1451    충청홍성대리점  정미진  4080000  2706000     2     220
2   KI1534    경기화성대리점  경인선   600000  2214000     1     320
3   KI1636    강원속초대리점  이동권  3720000  2870000     3     110
4   KI1735    경기안양대리점  강준석  4800000  2296000     1     134
5   KI1875   제주제주시대리점  민경수  3420000  2346000     4     210
6   KI1917    경기광주대리점  김진혜  1292000  1518000     1     110
7   KI2032    경기평택대리점  고유정  2736000  2139000     2      90
8   KI2153   경기의정부대리점  김은향  1368000  2484000     1     183
9   KI2214    경기성남대리점  이준수  1976000  1518000     3      73
10  KI2313  제주서귀포시대리점  온지수   152000   945000     1      52
11  KI2433    경기계양대리점  이희영  1833000  1404000     1     110
12  KI2512    경기평촌대리점  강백호  4320000  2312000     3     240
13  KI2671  제주서귀포시대리점  주은명  4040000  4760000     4      50
14  KI2776   경기남양주대리점  김수진  8160000  4352000     2     354
15  KI2870   경기구리시대리점  박진형  6000000  3400000     2     143
16  KI2910    강원춘천대리점  김은향  4800000  4896000     1     176
17  KI3030    강원영동대리점  전수창  4560000  3128000     2      98
18  KI3131    경기하남대리점  김민정  2750000  7268000     3     293
19  KI3252    강원포천대리점  서가은  2420000  4740000     4     240

In [70]:
# 총 판매수량 > 250 조회
sample_df[sample_df['총 판매수량'] > 250]

   Sap Co.       대리점 영업사원       전월       금월  TEAM  총 판매수량
2   KI1534   경기화성대리점  경인선   600000  2214000     1     320
14  KI2776  경기남양주대리점  김수진  8160000  4352000     2     354
18  KI3131   경기하남대리점  김민정  2750000  7268000     3     293

In [74]:
# 2 ~ 3 행 조회
sample_df.loc[2:3]

  Sap Co.      대리점 영업사원       전월       금월  TEAM  총 판매수량
2  KI1534  경기화성대리점  경인선   600000  2214000     1     320
3  KI1636  강원속초대리점  이동권  3720000  2870000     3     110

In [86]:
# 금월 컬럼 조회
sample_df.금월
sample_df['금월']

0     2952000
1     2706000
2     2214000
3     2870000
4     2296000
5     2346000
6     1518000
7     2139000
8     2484000
9     1518000
10     945000
11    1404000
12    2312000
13    4760000
14    4352000
15    3400000
16    4896000
17    3128000
18    7268000
19    4740000
Name: 금월, dtype: int64

In [88]:
# 2 ~ 3 행 조회, 대리점명, 총 판매수량
sample_df.loc[2:3, ['대리점', '총 판매수량']]
sample_df.iloc[2:4, [1,6]]

       대리점  총 판매수량
2  경기화성대리점     320
3  강원속초대리점     110

In [92]:
# Nate => Torres 변경
friend_df.iloc[1,0] = "Torres"
friend_df

     name  age        job
0    Jhon   25    student
1  Torres   30    teacher
2   Jenny   30  developer

In [ ]:
# 3 번 행 추가
friend_df.loc[3] = ["Mike", 30, "student"]
friend_df

In [103]:
# colume 추가
friend_df['addr'] = ['서울', '경기', '부산', '대구']
friend_df

     name        job addr
0    Jhon    student   서울
1  Torres    teacher   경기
2   Jenny  developer   부산
3    Mike    student   대구

In [ ]:
# age colume 제거 inplace => 원본 변경
friend_df.drop("age", axis=1, inplace=True)
friend_df.drop(columns="age", inplace=True)

In [106]:
friend_df

     name        job addr
0    Jhon    student   서울
1  Torres    teacher   경기
2   Jenny  developer   부산
3    Mike    student   대구

In [108]:
# 과학 컬럼 추가
student_df['과학'] = ['40', '50', '60']

In [113]:
student_df.to_csv("./data/student.csv", index=False)

In [115]:
student_df

   국어  영어  수학  과학
0  15  45  36  40
1  25  55  46  50
2  35  65  56  60

In [114]:
student_df1 = pd.read_csv("./data/student.csv")
student_df1

   국어  영어  수학  과학
0  15  45  36  40
1  25  55  46  50
2  35  65  56  60