In [ ]:
# !pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\source\pythonsource\.venv\Lib\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in c:\source\pythonsource\.venv\Lib\site-packages (from seaborn) (3.0.1)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\source\pythonsource\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\source\pythonsource\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\source\pythonsource\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\source\pythonsource\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.8-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 8.3/8.3 MB 52.6 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 56.3 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.1.1-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 50.8 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2 seaborn-0.13.2

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
import pandas as pd
import seaborn as sns

## subset
- head(n) / tail(n) / sample() / nlargest() / nsmallest()
- iloc[], loc[]

In [20]:
sample_df = pd.read_excel("./data/sample.xlsx")
sample_df.head()

  Sap Co.      대리점 영업사원       전월       금월  TEAM  총 판매수량
0  KI1316  경기수원대리점  이기정  1720000  2952000     1     123
1  KI1451  충청홍성대리점  정미진  4080000  2706000     2     220
2  KI1534  경기화성대리점  경인선   600000  2214000     1     320
3  KI1636  강원속초대리점  이동권  3720000  2870000     3     110
4  KI1735  경기안양대리점  강준석  4800000  2296000     1     134

In [ ]:
# 무작위 샘플
sample_df.sample(frac=0.1) # 확률

  Sap Co.       대리점 영업사원       전월       금월  TEAM  총 판매수량
0  KI1316   경기수원대리점  이기정  1720000  2952000     1     123
8  KI2153  경기의정부대리점  김은향  1368000  2484000     1     183

In [12]:
sample_df.nlargest(n=2, columns="전월")

   Sap Co.       대리점 영업사원       전월       금월  TEAM  총 판매수량
14  KI2776  경기남양주대리점  김수진  8160000  4352000     2     354
15  KI2870  경기구리시대리점  박진형  6000000  3400000     2     143

In [13]:
sample_df.nsmallest(n=2, columns="전월")

   Sap Co.        대리점 영업사원      전월       금월  TEAM  총 판매수량
10  KI2313  제주서귀포시대리점  온지수  152000   945000     1      52
2   KI1534    경기화성대리점  경인선  600000  2214000     1     320

In [15]:
sample_df.columns

Index(['Sap Co.', '대리점', '영업사원', '전월', '금월', 'TEAM', '총 판매수량'], dtype='str')

In [ ]:
# 대리점, 영업사원, 전월, 금월 컬럼 추출

# sample_df[['대리점', '영업사원', '전월', '금월']]
# sample_df.iloc[:,1:5]
sample_df.loc[:,"대리점":"금월"]

          대리점 영업사원       전월       금월
0     경기수원대리점  이기정  1720000  2952000
1     충청홍성대리점  정미진  4080000  2706000
2     경기화성대리점  경인선   600000  2214000
3     강원속초대리점  이동권  3720000  2870000
4     경기안양대리점  강준석  4800000  2296000
5    제주제주시대리점  민경수  3420000  2346000
6     경기광주대리점  김진혜  1292000  1518000
7     경기평택대리점  고유정  2736000  2139000
8    경기의정부대리점  김은향  1368000  2484000
9     경기성남대리점  이준수  1976000  1518000
10  제주서귀포시대리점  온지수   152000   945000
11    경기계양대리점  이희영  1833000  1404000
12    경기평촌대리점  강백호  4320000  2312000
13  제주서귀포시대리점  주은명  4040000  4760000
14   경기남양주대리점  김수진  8160000  4352000
15   경기구리시대리점  박진형  6000000  3400000
16    강원춘천대리점  김은향  4800000  4896000
17    강원영동대리점  전수창  4560000  3128000
18    경기하남대리점  김민정  2750000  7268000
19    강원포천대리점  서가은  2420000  4740000

In [22]:
list1 = list('abcde')
list1

['a', 'b', 'c', 'd', 'e']

In [28]:
# 중복 데이터 제거 후 추출
df = pd.DataFrame({"a":[4, 5, 6, 6], "b": [7, 8, 9, 9], "c": [10, 11, 12, 12]}, index=list('abcd'))
df

   a  b   c
a  4  7  10
b  5  8  11
c  6  9  12
d  6  9  12

In [30]:
df.drop_duplicates("a", inplace=True)

In [31]:
df

   a  b   c
a  4  7  10
b  5  8  11
c  6  9  12

In [34]:
# seaborn
iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [35]:
# 전체 행, 열 수
iris_df.shape

(150, 5)

In [38]:
# species 종류별 데이터 개수
iris_df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [42]:
iris_df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [43]:
iris_df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [50]:
iris_df.quantile([0.25, 0.75], numeric_only=True)

      sepal_length  sepal_width  petal_length  petal_width
0.25           5.1          2.8           1.6          0.3
0.75           6.4          3.3           5.1          1.8

In [51]:
# null? not null?
df = pd.DataFrame({"a":[4, 5, 6, 6], "b": [7, 8, 9, 9], "c": [10, 11, 12, 12]}, index=list('abcd'))
df

   a  b   c
a  4  7  10
b  5  8  11
c  6  9  12
d  6  9  12

In [52]:
# b 값이 7 이 아닌 데이터
df[df.b != 7]

   a  b   c
b  5  8  11
c  6  9  12
d  6  9  12

In [ ]:
# b 값이 7 이 아닌 a, b 칼럼만 조회
df.loc[df.b != 7, "a":"b"]

   a  b
b  5  8
c  6  9
d  6  9

In [57]:
# a 칼럼에 5 가 들어있는지 확인
df[df.a.isin([5])]

   a  b   c
b  5  8  11

In [60]:
# isna(), isnull()
# df.isna()
df.isnull()

# a 칼럼이 null 인지 확인
df.a.isnull()

a    False
b    False
c    False
d    False
Name: a, dtype: bool

In [61]:
df[df.isnull()]

    a   b   c
a NaN NaN NaN
b NaN NaN NaN
c NaN NaN NaN
d NaN NaN NaN

In [63]:
df = pd.DataFrame({"a":[4, 5, 6, 6, pd.NA], "b":[7, 8, pd.NA, 9, 9], "c":[10, 11, 12, pd.NaT, 12]}, index=[1, 2, 3, 4, 5])
df

      a     b    c
1     4     7   10
2     5     8   11
3     6  <NA>   12
4     6     9  NaT
5  <NA>     9   12

In [64]:
df.isna()

       a      b      c
1  False  False  False
2  False  False  False
3  False   True  False
4  False  False   True
5   True  False  False

In [ ]:
df.a.isna()
df.isna().sum() # 더하기

a    1
b    1
c    1
dtype: int64

In [69]:
df.notna()
df.notnull()

       a      b      c
1   True   True   True
2   True   True   True
3   True  False   True
4   True   True  False
5  False   True   True

In [ ]:
# null 들어있는 행 삭제
df.dropna()

   a  b   c
1  4  7  10
2  5  8  11

In [ ]:
# 열 기준으로 삭제
df.dropna(axis=1)

In [71]:
# null 이면 특정 값으로 채우기
df.fillna(0)

   a  b   c
1  4  7  10
2  5  8  11
3  6  0  12
4  6  9   0
5  0  9  12

In [80]:
df=sns.load_dataset("mpg")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [82]:
df.groupby("origin").count()
df.groupby("origin").size()
df.groupby("origin")['weight'].mean()
df.groupby(["origin", "model_year"])['cylinders'].mean()
df.groupby("origin")['horsepower'].agg(['sum', 'mean', 'std'])

            sum        mean        std
origin
europe   5478.0   80.558824  20.157871
japan    6307.0   79.835443  17.819199
usa     29167.0  119.048980  39.897790

In [74]:
student_list = {
    "name":["John", "Nate", "Abraham", "Brian", "Janny", "Yuna", "Jeniffer", "Edward", "Zara", "Wendy", "Sera"],
    "major":["Computer Science", "Computer Science", "Physics", "Psychology", "Economics", "Economics", "Computer Science", "Psychology", "Physics", "Physics", "Economics"],
    "gender":["male", "male", "male", "male", "female", "female", "female", "male", "male", "female", "female"]
}
df = pd.DataFrame(student_list)
df

        name             major  gender
0       John  Computer Science    male
1       Nate  Computer Science    male
2    Abraham           Physics    male
3      Brian        Psychology    male
4      Janny         Economics  female
5       Yuna         Economics  female
6   Jeniffer  Computer Science  female
7     Edward        Psychology    male
8       Zara           Physics    male
9      Wendy           Physics  female
10      Sera         Economics  female

In [77]:
df.groupby("major")['name'].count()

major
Computer Science    3
Economics           3
Physics             3
Psychology          2
Name: name, dtype: int64

In [78]:
df.groupby("gender")['name'].count()

gender
female    5
male      6
Name: name, dtype: int64

In [83]:
df = pd.DataFrame({"yyyy-mm-dd":['2005-09-08', '2007-10-05', '2012-12-20']})
df

   yyyy-mm-dd
0  2005-09-08
1  2007-10-05
2  2012-12-20

In [91]:
def extract_year(value):
    return value.split("-")[0]

In [92]:
# year 컬럼 생성
df['year'] = df['yyyy-mm-dd'].apply(extract_year)
df

   yyyy-mm-dd  year
0  2005-09-08  2005
1  2007-10-05  2007
2  2012-12-20  2012

In [96]:
def get_age(year, curr_year):
    return curr_year -int(year)

In [97]:
df.dtypes

yyyy-mm-dd    str
year          str
dtype: object

In [99]:
# age 칼럼 생성
df['age'] =  df['year'].apply(get_age, curr_year = 2026)
df

   yyyy-mm-dd  year  age
0  2005-09-08  2005   21
1  2007-10-05  2007   19
2  2012-12-20  2012   14

In [100]:
df.dtypes

yyyy-mm-dd      str
year            str
age           int64
dtype: object

In [101]:
df = pd.DataFrame({"영어":[60, 70], "수학":[100, 50],}, index=["Dave", "David"])
df

       영어   수학
Dave   60  100
David  70   50

In [104]:
def func(df):
    # print(df.index)
    # print(df.values)
    df['영어'] = 80
    return df

In [103]:
df.apply(func, axis=1)

Index(['영어', '수학'], dtype='str')
[ 60 100]
Index(['영어', '수학'], dtype='str')
[70 50]

       영어   수학
Dave   60  100
David  70   50

In [107]:
df2 = df.apply(func, axis=1)
df2

       영어   수학
Dave   80  100
David  80   50